# All CI will execute from here using workflow_call

name: DevSecOps

on:
    push:
        branches:
            - main

jobs:
    
    # code-quality:
    #     uses: ./.github/workflows/code-quality.yml

    # secrets-scan:
    #     uses: ./.github/workflows/secret-scanning.yml
        
    # dependecy-check:
    #     uses: ./.github/workflows/dependency-scan.yml

    # dockerfile-scan:
    #     uses: ./.github/workflows/dockerfile-scan.yml
    #     secrets: inherit

    dockerbuild-push:
        uses: ./.github/workflows/docker-build.yml
        secrets: inherit